using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml.Linq;

namespace SharpScript.Scripting
{
    /// <summary>
    /// What a new script starts as, and the one generated file that ties the project to the Rhino
    /// running on this machine. Kept apart from the project itself so the text an author first
    /// reads can be read here in one piece.
    /// </summary>
    internal static class ProjectTemplates
    {
        /// <summary>
        /// The usings every file in the script starts with. This is an ordinary project file, so
        /// it can be edited: adding a line here is how a script reaches a namespace it uses often
        /// without repeating the using in each file.
        /// </summary>
        public const string Usings = @"// Namespaces every file in this script can use.
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using Rhino;
global using Rhino.Geometry;
global using Grasshopper;
global using Grasshopper.Kernel;
global using Grasshopper.Kernel.Data;
global using Grasshopper.Kernel.Types;
global using SharpScript;
";

        public const string Project = @"<Project Sdk=""Microsoft.NET.Sdk"">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>Script</AssemblyName>
  </PropertyGroup>

  <!--
    Rhino, Grasshopper and the script API arrive through Directory.Build.targets, which
    SharpScript regenerates for whichever Rhino is running. Add NuGet packages below and press
    Compile: they are restored and used by the component as well as by the IDE.
  -->
  <ItemGroup>
    <!-- <PackageReference Include=""MathNet.Numerics"" Version=""5.0.0"" /> -->
  </ItemGroup>

</Project>
";

        public const string Source = @"public class Script : ScriptBase
{
    public void RunScript(
        [Description(""Radius of the circle"")] [Default(10.0)] double radius,
        [Description(""Plane the circle sits on"")] [Optional] Plane plane,
        out Circle result)
    {
        if (!plane.IsValid) plane = Plane.WorldXY;

        result = new Circle(plane, radius);
        Print(""Circumference: {0:F2}"", result.Circumference);
    }
}
";

        /// <summary>
        /// Points the project at the Rhino that is running right now rather than at a NuGet
        /// package of some other version. Regenerated on every mirror, which is what keeps the
        /// csproj the author edits free of machine specific paths.
        /// </summary>
        public static string BuildTargets()
        {
            var references = HostReferences().Select(path => new XElement("Reference",
                new XAttribute("Include", Path.GetFileNameWithoutExtension(path)),
                new XElement("HintPath", path),
                new XElement("Private", "false")));

            var document = new XDocument(
                new XComment(" Generated by SharpScript. Edits here are overwritten. "),
                new XElement("Project", new XElement("ItemGroup", references)));

            return document.ToString();
        }

        /// <summary>
        /// The Rhino side assemblies a script may use. The compiler takes the same list, so what
        /// the IDE resolves from the csproj and what the component compiles against stay equal.
        /// </summary>
        public static IEnumerable<string> HostReferences()
        {
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var path in Candidates())
            {
                if (string.IsNullOrEmpty(path) || !File.Exists(path)) continue;
                if (seen.Add(Path.GetFileNameWithoutExtension(path))) yield return path;
            }
        }

        static IEnumerable<string> Candidates()
        {
            var rhinoCommon = typeof(Rhino.RhinoDoc).Assembly.Location;
            var grasshopper = typeof(Grasshopper.Kernel.GH_Component).Assembly.Location;

            yield return rhinoCommon;
            yield return grasshopper;
            yield return typeof(ProjectTemplates).Assembly.Location;

            var grasshopperFolder = Path.GetDirectoryName(grasshopper);
            if (grasshopperFolder != null) yield return Path.Combine(grasshopperFolder, "GH_IO.dll");

            var rhinoFolder = Path.GetDirectoryName(rhinoCommon);
            if (rhinoFolder == null) yield break;

            yield return Path.Combine(rhinoFolder, "Rhino.UI.dll");
            yield return Path.Combine(rhinoFolder, "Eto.dll");
        }
    }
}
